name: Build and Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install backend dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run backend tests
        run: npm test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 5

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t iapocchallenge.azurecr.io/myapp:${{ github.sha }} .

      - name: Login to Azure Container Registry
        run: az acr login --name iapocchallenge

      - name: Push Docker image to ACR
        run: |
          docker push iapocchallenge.azurecr.io/myapp:${{ github.sha }}

      - name: Configure Azure Web App to use Docker image and set environment variables
        run: |
          az webapp config container set \
            --name IACHALLENGE70 \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --container-image-name iapocchallenge.azurecr.io/myapp:${{ github.sha }}

          az webapp config appsettings set \
            --name IACHALLENGE70 \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --settings ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
                        REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} \
                        SALT_ROUNDS=${{ secrets.SALT_ROUNDS }}
                        API_BASE_URL=${{ secrets.API_BASE_URL }}
                        OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}
                        TENANT_SUBDOMAIN=${{secrets.TENANT_SUBDOMAIN}}
                        CLOUD_INSTANCE=${{secrets.CLOUD_INSTANCE}}
                        REDIRECT_URI=${{secrets.REDIRECT_URI}}
                        POST_LOGOUT_REDIRECT_URI=${{secrets.POST_LOGOUT_REDIRECT_URI}}
                        GRAPH_API_ENDPOINT=${{secrets.GRAPH_API_ENDPOINT}}
                        EXPRESS_SESSION_SECRET=${{secrets.EXPRESS_SESSION_SECRET}}


      - name: Restart Azure Web App
        run: az webapp restart --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name IACHALLENGE70
