name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t iapocchallenge.azurecr.io/myapp:${{ github.sha }} .

      - name: Login to Azure Container Registry
        run: az acr login --name iapocchallenge

      - name: Push Docker image to ACR
        run: |
          docker push iapocchallenge.azurecr.io/myapp:${{ github.sha }}

      - name: Configure Azure Web App to use Docker image
        run: |
          az webapp config container set \
            --name IArg70Cluster \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name iapocchallenge.azurecr.io/myapp:${{ github.sha }}

      - name: Restart Azure Web App
        run: |
          az webapp restart \
            --name IArg70Cluster \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}